package main

/**
 * Description: 获取武将
 * @return map
 */
func GetHeroesData() map[string]string {
	HeroDb := make(map[string]string)
	HeroDb["1"] = "关羽"
	HeroDb["2"] = "白起"
	HeroDb["3"] = "项羽"
	HeroDb["4"] = "曹操"
	HeroDb["5"] = "岳飞"
	HeroDb["6"] = "吕布"
	HeroDb["7"] = "赵云"
	HeroDb["8"] = "嬴政"
	HeroDb["9"] = "霍去病"
	HeroDb["10"] = "张辽"
	HeroDb["11"] = "诸葛亮"
	HeroDb["12"] = "韩信"
	HeroDb["13"] = "张飞"
	HeroDb["14"] = "卫青"
	HeroDb["15"] = "姜子牙"
	HeroDb["16"] = "周瑜"
	HeroDb["17"] = "李靖"
	HeroDb["18"] = "陆逊"
	HeroDb["19"] = "司马懿"
	HeroDb["20"] = "刘备"
	HeroDb["21"] = "李世民"
	HeroDb["22"] = "张良"
	HeroDb["23"] = "廉颇"
	HeroDb["24"] = "贾诩"
	HeroDb["25"] = "孙膑"
	HeroDb["26"] = "秦琼"
	HeroDb["27"] = "庞统"
	HeroDb["28"] = "萧何"
	HeroDb["29"] = "蒙恬"
	HeroDb["30"] = "黄忠"
	HeroDb["31"] = "孙武"
	HeroDb["32"] = "戚继光"
	HeroDb["33"] = "郭嘉"
	HeroDb["34"] = "马超"
	HeroDb["35"] = "刘邦"
	HeroDb["36"] = "李元霸"
	HeroDb["37"] = "夏侯惇"
	HeroDb["38"] = "甘宁"
	HeroDb["39"] = "花木兰"
	HeroDb["40"] = "武则天"
	HeroDb["41"] = "武松"
	HeroDb["42"] = "许褚"
	HeroDb["43"] = "典韦"
	HeroDb["44"] = "孙尚香"
	HeroDb["45"] = "华佗"
	HeroDb["46"] = "蔡文姬"
	HeroDb["47"] = "貂蝉"
	HeroDb["48"] = "西施"
	HeroDb["49"] = "王昭君"
	HeroDb["50"] = "杨玉环"
	return HeroDb
}
